/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author LENOVO
 */;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import kodeprogram.Admin;
public class ForAdmin extends javax.swing.JFrame {
private static final long serialVersionUID = 1L;
    /**
     * Creates new form NewJFrame
     */
    private Admin admin;

    public ForAdmin() {
        initComponents();
        admin = new Admin(this);
        admin.isitabel2();
        admin.isitabel();   
    }

    public JTable getTabelStok(){
        return tabelStok;
    }
    public JTable getTabelCustomer(){
        return tabelCustomer;
    }
    public JTable getTabelTambah(){
        return tabelTambah;
    }
    public JTextField getIdbrg(){ 
        return id_barang;
    }
    public JTextField getStok(){
        return tambahstok;
    }
    public JTextField getNo(){
        return no;
    }
    public JTextField getTextHarga(){
        return TextHarga;
    }
    public JTextField getTextNama(){
        return TextNama;
    }
    public JTextField getTextNoHP(){
        return TextNoHP;
    }
    public JTextField getNoBeli(){
        return noBeli;
    }
    public JTextField getTextID(){
    return idbrg;
    }
   
  
    public JButton getButtonBeli(){
        return ButtonBeli;
    }
    public JButton getButtonTidakbeli(){
        return ButtonTidakbeli;
    }
    public JComboBox getBoxBayar(){
        return BoxBayar;
    }
    public JComboBox getBoxJenisBeli(){
        return BoxJenisBeli1;
    }
    public JTable getTableCustomer(){
        
       return tabelCustomer;
    }
    public JTextField getTanggalBeli2(){
        return TextTanggalBeli;
    }

    public JTextField getJumlah1(){
        return TextJumlah;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("uas_ppbo?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        barangAdminQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM BarangAdmin b");
        barangAdminList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : barangAdminQuery.getResultList();
        tab3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelStok = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTambah = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        id_barang = new javax.swing.JTextField();
        tambahstok = new javax.swing.JTextField();
        simpan_stok = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ButtonBeli = new javax.swing.JButton();
        ButtonTidakbeli = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        noBeli = new javax.swing.JTextField();
        TextNama = new javax.swing.JTextField();
        TextNoHP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TextHarga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextTanggalBeli = new javax.swing.JTextField();
        BoxBayar = new javax.swing.JComboBox<>();
        BoxJenisBeli1 = new javax.swing.JComboBox<>();
        idbrg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        no_label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCustomer = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TextJumlah = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("DAFTAR STOK");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, barangAdminList, tabelStok);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${namapaket}"));
        columnBinding.setColumnName("Namapaket");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${stok}"));
        columnBinding.setColumnName("Stok");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(tabelStok);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("TAMBAH STOK");

        tabelTambah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelTambah);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("No");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("ID Barang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Tambahan");

        no.setEditable(false);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        tambahstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahstokActionPerformed(evt);
            }
        });

        simpan_stok.setText("Simpan");
        simpan_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_stokActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(simpan_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                    .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_barang)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahstok, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel20)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tambahstok, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(simpan_stok)
                    .addComponent(batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        tab3.addTab("stok", jPanel7);

        ButtonBeli.setText("Simpan");
        ButtonBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBeliActionPerformed(evt);
            }
        });

        ButtonTidakbeli.setText("Hapus");
        ButtonTidakbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTidakbeliActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(185, 141, 35));
        jLabel13.setText("Nama");

        noBeli.setEditable(false);
        noBeli.setBackground(new java.awt.Color(204, 204, 204));
        noBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBeliActionPerformed(evt);
            }
        });

        TextNama.setBackground(new java.awt.Color(204, 204, 204));
        TextNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNamaActionPerformed(evt);
            }
        });

        TextNoHP.setBackground(new java.awt.Color(204, 204, 204));
        TextNoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNoHPActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(185, 141, 35));
        jLabel5.setText("Harga");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(185, 141, 35));
        jLabel14.setText("No. Hp");

        TextHarga.setEditable(false);
        TextHarga.setBackground(new java.awt.Color(204, 204, 204));
        TextHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHargaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(185, 141, 35));
        jLabel15.setText("Jenis Pembelian");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(185, 141, 35));
        jLabel7.setText("Metode Bayar");

        TextTanggalBeli.setBackground(new java.awt.Color(204, 204, 204));
        TextTanggalBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTanggalBeliActionPerformed(evt);
            }
        });

        BoxBayar.setBackground(new java.awt.Color(204, 204, 204));
        BoxBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank", "GoPay", "Indomaret" }));
        BoxBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxBayarActionPerformed(evt);
            }
        });

        BoxJenisBeli1.setBackground(new java.awt.Color(204, 204, 204));
        BoxJenisBeli1.setMaximumRowCount(23);
        BoxJenisBeli1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JOOX 7 Hari", "JOOX 30 Hari", "JOOX 90 Hari", "JOOX 180 Hari", "JOOX 360 Hari", "Spotify Mini/hari", "Spotify Individual/2bulan", "Spotify Duo/2bulan", "Spotify Family/2bulan", "Youtube Music Premium/1bulan", " ", " " }));
        BoxJenisBeli1.setToolTipText("");
        BoxJenisBeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxJenisBeli1ActionPerformed(evt);
            }
        });

        idbrg.setBackground(new java.awt.Color(204, 204, 204));
        idbrg.setForeground(new java.awt.Color(109, 109, 109));
        idbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbrgActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(185, 141, 35));
        jLabel6.setText("Tanggal Beli");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(185, 141, 35));
        jLabel16.setText("DAFTAR PESANAN");
        jLabel16.setToolTipText("");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(255, 204, 204), java.awt.Color.gray, java.awt.Color.white));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(185, 141, 35));
        jLabel17.setText("ID");
        jLabel17.setRequestFocusEnabled(false);

        no_label.setBackground(java.awt.Color.orange);
        no_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        no_label.setForeground(new java.awt.Color(185, 141, 35));
        no_label.setText("No");

        tabelCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelCustomer);

        jLabel8.setBackground(new java.awt.Color(185, 141, 35));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(185, 141, 35));
        jLabel8.setText("Jumlah");

        TextJumlah.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ButtonBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(ButtonTidakbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(no_label))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextNama)
                                            .addComponent(noBeli)
                                            .addComponent(TextNoHP)
                                            .addComponent(BoxJenisBeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idbrg)
                                            .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BoxBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextTanggalBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(77, 77, 77)))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxJenisBeli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(TextJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(BoxBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextTanggalBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonBeli)
                    .addComponent(ButtonTidakbeli)
                    .addComponent(Edit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab3.addTab("pesanan", jPanel4);

        jLabel22.setFont(new java.awt.Font("Rage Italic", 1, 90)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 178, 97));
        jLabel22.setText("hearTHEsong`");
        jLabel22.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_stokActionPerformed
        admin.insert();
        admin.isitabel2();
    }//GEN-LAST:event_simpan_stokActionPerformed

    private void tambahstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahstokActionPerformed
    
    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void ButtonTidakbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTidakbeliActionPerformed
       admin.delete();
       admin.isitabel();
       admin.kosongkan_pesanan();
    }//GEN-LAST:event_ButtonTidakbeliActionPerformed

    private void ButtonBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBeliActionPerformed
    admin.insert2();
    admin.isitabel();
    }//GEN-LAST:event_ButtonBeliActionPerformed

    private void noBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noBeliActionPerformed

    private void TextNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNamaActionPerformed

    private void TextNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNoHPActionPerformed

    private void TextHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHargaActionPerformed

    private void TextTanggalBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTanggalBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTanggalBeliActionPerformed

    private void BoxJenisBeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxJenisBeli1ActionPerformed
        String jenis; String nilai; String id = null; 
        jenis = String.valueOf(BoxJenisBeli1.getSelectedItem());
        
        switch(jenis){
            case ("JOOX 7 Hari"):
            nilai="10000";
            id="1";
            break;
            case("JOOX 30 Hari"):
            nilai="35000";
            id="2";
            break;
            case("JOOX 90 Hari"):
            nilai="93000";
            id="3";
            break;
            case("JOOX 180 Hari"):
            nilai="181000";
            id="4";
            break;
            case("JOOX 360 Hari"):
            nilai="300000";
            id="5";
            break;
            case("Spotify Mini/hari"):
            nilai="3000";
            id="6";
            break;
            case("Spotify Individual/2bulan"):
            nilai="55000";
            id="7";
            break;
            case("Spotify Duo/2bulan"):
            nilai="73000";
            id="8";
            break;
            case("Spotify Family/2bulan"):
            nilai="89000";
            id="9";
            break;
            case("Youtube Music Premium/1bulan"):
            nilai="50000";
            id="10";
            break;
            default:
            nilai="Tidak Terdaftar";
        }
        TextHarga.setText(""+nilai);
        idbrg.setText(""+id);
    }//GEN-LAST:event_BoxJenisBeli1ActionPerformed

    private void idbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbrgActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
  admin.update();
  admin.isitabel();
  admin.kosongkan_pesanan();
    }//GEN-LAST:event_EditActionPerformed

    private void BoxBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxBayarActionPerformed

    private void tabelCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCustomerMouseClicked
        int baris = tabelCustomer.rowAtPoint(evt.getPoint());
        String nomor = tabelCustomer.getValueAt(baris, 0).toString();
        noBeli.setText(String.valueOf(nomor));
        String nama1 = tabelCustomer.getValueAt(baris, 1).toString();
        TextNama.setText(nama1);
        String NoHp = tabelCustomer.getValueAt(baris, 2).toString();
        TextNoHP.setText(NoHp);
        String jenis1 = tabelCustomer.getValueAt(baris, 3).toString();
        BoxJenisBeli1.setSelectedItem(jenis1);
        String id1 = tabelCustomer.getValueAt(baris, 4).toString();
        idbrg.setText(id1);
        String harga1 = tabelCustomer.getValueAt(baris, 5).toString();
        TextHarga.setText(harga1);
        String jumlah1 = tabelCustomer.getValueAt(baris, 6).toString();
        TextJumlah.setText(jumlah1);
        String metbayar1 = tabelCustomer.getValueAt(baris, 7).toString();
        BoxBayar.setSelectedItem(metbayar1);
        String tanggal1 = tabelCustomer.getValueAt(baris, 8).toString();
        TextTanggalBeli.setText(tanggal1);

    }//GEN-LAST:event_tabelCustomerMouseClicked

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ForAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxBayar;
    private javax.swing.JComboBox<String> BoxJenisBeli1;
    private javax.swing.JButton ButtonBeli;
    private javax.swing.JButton ButtonTidakbeli;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField TextHarga;
    private javax.swing.JTextField TextJumlah;
    private javax.swing.JTextField TextNama;
    private javax.swing.JTextField TextNoHP;
    private javax.swing.JTextField TextTanggalBeli;
    private java.util.List<view.BarangAdmin> barangAdminList;
    private javax.persistence.Query barangAdminQuery;
    private javax.swing.JButton batal;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id_barang;
    private javax.swing.JTextField idbrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField no;
    private javax.swing.JTextField noBeli;
    private javax.swing.JLabel no_label;
    private javax.swing.JButton simpan_stok;
    private javax.swing.JTabbedPane tab3;
    private javax.swing.JTable tabelCustomer;
    private javax.swing.JTable tabelStok;
    private javax.swing.JTable tabelTambah;
    private javax.swing.JTextField tambahstok;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

   
}
